name: Publish Package to GitHub Packages

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # Cập nhật phiên bản Flutter của bạn

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Publish to GitHub Packages
        run: |
          dart pub publish --server=https://dart.pkg.github.com/NguyenMinhDuc163/Fire-guard-mobile
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
